---
IDP_METADATA_PATH: |
    <xml> this is some idp xml data </xml>
DISPLAY_NAME_ATTRIBUTE: 'def'
GROUP_ATTRIBUTE: 'ghi'
MAX_AUTH_LIFETIME: 10
USERNAME_ATTRIBUTE: 'jkl'
EMAIL_ATTRIBUTE: 'mno'
LOGOUT_URL: 'https://www.example.com/logout'
ADVANCED_CONFIGURATION: []
ENCRYPTION_DATA: []
USERNAME_CASE_CONVENTION: 'uppercase'
BINDING: 'Post'
SAML_CUSTOM_ATTRIBUTES: []
